# Generated by Django 5.0.6 on 2024-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('desc', models.TextField()),
                ('images', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
